### ISSUE TITLE
Error when using sh. Script should use Bash by default.

### ISSUE THREAD

**Issue by StephanMeijer** [mchav/with#12]
Bash works fine, using sh does not.

```
/usr/bin/with: 12: /usr/bin/with: Syntax error: "(" unexpected (expecting "fi")
```

**Comment by mchav** [comment]
Thank you. That was a an error with the expression statement. Fixed with most recent commit and now works with sh.

**Comment by maturanomx** [comment]
I'm having the same error. Tried with `master` on commit 61d059d

I see will manage on #15
