### ISSUE TITLE
Shellcheck

### ISSUE THREAD

**Issue by z0rc** [mchav/with#17]
Please use https://github.com/koalaman/shellcheck on this script. It points some nasty things like:

```
In with line 35:
          ${prefix[@]} ;;
          ^-- SC2068: Double quote array expansions to avoid re-splitting elements.
          ^-- SC2039: In POSIX sh, array references are undefined.
```

It's just the single warning, full list have more than 10 of them.

**Comment by mchav** [comment]
Added a note on the wiki to always use shellcheck.
