### ISSUE TITLE
Syntax error on Linux Ubuntu with #!/usr/bin/env sh

### ISSUE THREAD

**Issue by Manaphy91** [mchav/with#18]
Hi, on Ubuntu 14.04 LTS when I try to use `with` I obtain the following syntax error:
`with: 12: with: Syntax error: "(" unexpected (expecting "fi")`
If I try to replace `#!/usr/bin/env sh` with `#!/usr/bin/env bash` all the troubles go away.
I think I obtain that error because on Ubuntu sh is a link to dash shell.

**Comment by mchav** [comment]
Same problem as issue #15 
Keeping it at bash would be wise until we find a way to make it work on dash as well.

**Comment by mchav** [comment]
Closed in favour of #15
