### ISSUE TITLE
Add support for shell syntax in `:`-prefixed lines

### ISSUE THREAD

**Issue by eush77** [mchav/with#23]
``` sh
> : echo 1 | cat
1 | cat
> : echo 1 && echo 2
1 && echo 2
```

Expected output:

``` sh
> : echo 1 | cat
1
> : echo 1 && echo 2
1
2
```

**Comment by mchav** [comment]
I'll look at this soon but if anyone is interested in sending in a PR, I think it has to do with passing arguments to eval as a string. Probably this would require splitting options and then passing the array to eval.

**Comment by eush77** [comment]
Nice!
