### ISSUE TITLE
sed: 1: "s/%prefix%/curl -vvv ht ...": bad flag in substitute command: '/'

### ISSUE THREAD

**Issue by maturanomx** [mchav/with#41]
When use with programs with slashes in their parameters. Something like `with curl 'https://google.com'`

**Comment by desyncr** [comment]
I'm not sure you should use `with curl https://google.com`, but rather `with curl`.

What is happening is that `with` is trying to use `curl https://google.com` as your command prefix. Regardless I think a quick and easy fix would be to use:

```
sed -E -e "s|%prefix%|$__prefix|"
```

ie, `|` rather than `/`.

**Comment by trevorsibanda** [comment]
Fixed this in #43
